# Generated by Django 4.2.6 on 2023-10-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
