# Generated by Django 4.2.6 on 2023-10-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_participants_alter_expense_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='participants',
        ),
    ]
